# -*- coding: utf-8 -*-
"""PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Yliv5pKG4iOfvPLuo6ObYTarvT8Upzd

# Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
from sklearn.preprocessing import StandardScaler, LabelEncoder
import html
from wordcloud import WordCloud
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from collections import Counter
from google.colab import drive
import os
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
import tensorflow as tf
from sklearn.utils import class_weight
from sklearn.neural_network import MLPClassifier
from sklearn.utils import resample
from tensorflow import keras
from keras import layers, models, callbacks

drive.mount('/content/drive')

!pip install contractions
import contractions

!pip install gensim
import gensim
from gensim.models import Word2Vec

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

"""# EDA:  Exploratory Data Analysis"""

train = pd.read_csv("/content/drive/MyDrive/CSE440/PROJECT/DATASET/Training_data_2.csv")
test = pd.read_csv("/content/drive/MyDrive/CSE440/PROJECT/DATASET/Test_data.csv")

combined_df = pd.concat([train, test], axis=0)

combined_df.reset_index(drop=True, inplace=True)

combined_df.shape

combined_df.head()

combined_df.info()

combined_df = combined_df.dropna().reset_index(drop=True)
combined_df.isnull().sum()

combined_df = combined_df.drop_duplicates().reset_index(drop=True)
combined_df.duplicated().sum()

combined_df['News Topic'].value_counts()

topic_counts = combined_df['News Topic'].value_counts()
plt.figure(figsize=(10, 6))
plt.bar(topic_counts.index, topic_counts.values)
plt.title("Distribution of News Topics")
plt.xlabel("News Topic")
plt.ylabel("Number of Articles")
plt.show()

combined_df['word_count'] = combined_df['News Headline'].apply(lambda x: len(str(x).split()))
combined_df['word_count'].describe()

plt.figure(figsize=(10, 6))
sns.boxplot(x='News Topic', y='word_count', data=combined_df)
plt.title("Word Count Distribution per Topic")
plt.xlabel("News Topic")
plt.ylabel("Word Count per Headline")
plt.show()

def plot_top_ngrams(df, topic, n):
    subset = df[df['News Topic'] == topic]['News Headline']
    vec = CountVectorizer(ngram_range=(n, n)).fit(subset)
    bag_of_words = vec.transform(subset)
    sum_words = bag_of_words.sum(axis=0)
    words_freq = [(word, sum_words[0, idx]) for word, idx in vec.vocabulary_.items()]
    words_freq = sorted(words_freq, key=lambda x: x[1], reverse=True)[:10]
    words, counts = zip(*words_freq)
    plt.figure(figsize=(10, 6))
    sns.barplot(x=list(counts), y=list(words))
    plt.title(f"Top {n}-grams: {topic}")
    plt.show()

plot_top_ngrams(combined_df, "Sports", n=2)

plot_top_ngrams(combined_df, "World News", n=2)

plot_top_ngrams(combined_df, "Business", n=2)

plot_top_ngrams(combined_df, "Science and Technology", n=2)

def show_wordcloud(df, topic):
    text = " ".join(headline for headline in df[df['News Topic'] == topic]['News Headline'])
    wc = WordCloud(width=800, height=400, background_color='white', max_words=100).generate(text)
    plt.figure(figsize=(10, 6))
    plt.imshow(wc, interpolation='bilinear')
    plt.title(f"Word Cloud for {topic}")
    plt.axis('off')
    plt.show()

show_wordcloud(combined_df, "Sports")

show_wordcloud(combined_df, "World News")

show_wordcloud(combined_df, "Business")

show_wordcloud(combined_df, "Science and Technology")

def plot_topic_cooccurrence(df, topic, n_words=10):
    subset = df[df['News Topic'] == topic]['News Headline']
    vec = CountVectorizer(max_features=n_words)
    bow = vec.fit_transform(subset)
    matrix = (bow.T * bow).toarray()
    np.fill_diagonal(matrix, 0)
    names = vec.get_feature_names_out()
    df_matrix = pd.DataFrame(matrix, index=names, columns=names)
    plt.figure(figsize=(10, 6))
    sns.heatmap(df_matrix, annot=True, fmt='d', cmap="YlGnBu", cbar=False)
    plt.title(f"Word Co-occurrence: {topic} (Top {n_words} words)")
    plt.show()

plot_topic_cooccurrence(combined_df, 'Sports')

plot_topic_cooccurrence(combined_df, 'World News')

plot_topic_cooccurrence(combined_df, 'Business')

plot_topic_cooccurrence(combined_df, 'Science and Technology')

"""# Preprocessing"""

combined_df['text_no_preprocessing'] = combined_df['News Headline']
stop_words = set(stopwords.words('english'))

stemmer = PorterStemmer()
def extreme_preprocessing_stem(text):
    text = html.unescape(text)
    text = re.sub(r'html.*?news headlines:', '', text, flags=re.IGNORECASE | re.DOTALL)
    text = re.sub(r'<.*?>', '', text)
    text = contractions.fix(text)
    text = re.sub(r'[A-Z\s\/]+(\(Reuters\)|\(AFP\)|\(AP\)|--|-)\s*', ' ', text)
    text = text.lower()
    text = re.sub(r'[^a-z\s]', ' ', text)
    tokens = [stemmer.stem(word) for word in text.split() if word not in stop_words]
    return ' '.join(tokens)
combined_df['text_extreme_stem'] = combined_df['News Headline'].apply(extreme_preprocessing_stem)

lemmatizer = WordNetLemmatizer()
def optimum_preprocessing(text):
    text = html.unescape(text)
    text = re.sub(r'html.*?news headlines:', '', text, flags=re.IGNORECASE | re.DOTALL)
    text = re.sub(r'<.*?>', '', text)
    text = contractions.fix(text)
    text = re.sub(r'[A-Z\s\/]+(\(Reuters\)|\(AFP\)|\(AP\)|--|-)\s*', ' ', text)
    text = re.sub(r'[\$\£]\d+', ' MONEY ', text)
    text = re.sub(r'\d+%', ' PERCENT ', text)
    text = re.sub(r'\d+\s?(mb|gb|km|mph)', ' UNIT ', text, flags=re.IGNORECASE)
    text = text.lower()
    text = re.sub(r"'s\b", "", text)
    text = re.sub(r'[^a-z0-9\s]', '', text)
    tokens = [word for word in text.split() if word not in stop_words]
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    return ' '.join(tokens)
combined_df['text_optimum'] = combined_df['News Headline'].apply(optimum_preprocessing)

combined_df = combined_df.dropna().reset_index(drop=True)
combined_df = combined_df.drop_duplicates().reset_index(drop=True)
combined_df = combined_df[combined_df['text_extreme_stem'].str.strip() != ''].reset_index(drop=True)
combined_df = combined_df[combined_df['text_optimum'].str.strip() != ''].reset_index(drop=True)
le = LabelEncoder()
combined_df['topic_label'] = le.fit_transform(combined_df['News Topic'])
combined_df = combined_df.drop(columns=['News Headline', 'News Topic', 'word_count'])

combined_df.head()

"""# Word Representations"""

datasets = ['text_no_preprocessing', 'text_extreme_stem', 'text_optimum']

tfidf_results = {}
for col in datasets:
    tfidf_vectorizer = TfidfVectorizer(max_features=10000, ngram_range=(1, 2), min_df=3, max_df=0.8)
    X_tfidf = tfidf_vectorizer.fit_transform(combined_df[col].astype(str))
    tfidf_results[col] = X_tfidf

skipgram_results = {}
a = 1e-3
for col in datasets:
    tokenized_data = [text.split() for text in combined_df[col].astype(str)]
    model = Word2Vec(vector_size=100, window=5, sg=1, min_count=5)
    model.build_vocab(tokenized_data)
    model.train(tokenized_data, total_examples=model.corpus_count, epochs=10)
    all_words = []
    for s in tokenized_data:
        for w in s:
            all_words.append(w)
    counts = Counter(all_words)
    total = sum(counts.values())
    vectors = []
    for tokens in tokenized_data:
        word_vecs = []
        for w in tokens:
            if w in model.wv:
                raw_vector = model.wv[w]
                word_probability = counts[w] / total
                weight = a / (a + word_probability)
                weighted_vector = raw_vector * weight
                word_vecs.append(weighted_vector)
        vectors.append(np.mean(word_vecs, axis=0) if word_vecs else np.zeros(100))
    X = np.array(vectors)
    skipgram_results[col] = X

"""# Model training"""

TOTAL_ROWS = 95727
TEST_SIZE = 12000
TRAIN_VAL_LIMIT = TOTAL_ROWS - TEST_SIZE
y = combined_df['topic_label'].values
all_results_tfidf = []
all_results_skipgram = []

for name, X in tfidf_results.items():
    print(f"{'='*40}")
    print(f"DATASET: {name}")
    print(f"{'='*40}\n")
    X_train_val = X[:TRAIN_VAL_LIMIT]
    y_train_val = y[:TRAIN_VAL_LIMIT]
    X_test = X[TRAIN_VAL_LIMIT:]
    y_test = y[TRAIN_VAL_LIMIT:]
    X_train, X_val, y_train, y_val = train_test_split(
        X_train_val, y_train_val, test_size=0.15, random_state=42, stratify=y_train_val
    )
    best_c = 1.0
    best_val_f1 = 0
    c_options = [0.1, 1.0, 10.0]
    for c_val in c_options:
        lr = LogisticRegression(C=c_val, max_iter=1000, class_weight='balanced')
        lr.fit(X_train, y_train)
        val_preds = lr.predict(X_val)
        current_f1 = f1_score(y_val, val_preds, average='macro')
        if current_f1 > best_val_f1:
            best_val_f1 = current_f1
            best_c = c_val
    final_model = LogisticRegression(C=best_c, max_iter=1000, class_weight='balanced')
    final_model.fit(X_train_val, y_train_val)
    test_preds = final_model.predict(X_test)
    acc = accuracy_score(y_test, test_preds)
    f1 = f1_score(y_test, test_preds, average='macro')
    all_results_tfidf.append({
        'Model': 'Logistic Regression',
        'Dataset': name,
        'Accuracy': acc,
        'F1-Macro': f1
    })
    print(f"Accuracy: {acc:.4f}")
    print(f"F1-Score (Macro): {f1:.4f}\n")
    print("\nConfusion Matrix:\n")
    print(confusion_matrix(y_test, test_preds))
    print("\nClassification Report:\n")
    print(classification_report(y_test, test_preds))

for name, X in tfidf_results.items():
    print(f"{'='*40}")
    print(f"DATASET: {name}")
    print(f"{'='*40}\n")
    X_train_val, y_train_val = X[:TRAIN_VAL_LIMIT], y[:TRAIN_VAL_LIMIT]
    X_test, y_test = X[TRAIN_VAL_LIMIT:], y[TRAIN_VAL_LIMIT:]
    X_train, X_val, y_train, y_val = train_test_split(
        X_train_val, y_train_val, test_size=0.15, random_state=42, stratify=y_train_val
    )
    X_tune, y_tune = resample(X_train, y_train, n_samples=10000, random_state=42, stratify=y_train)
    tuning_params = {
        'lrs': [0.005, 0.001, 0.0005],
        'batches': [2048],
        'structs': [
            (256, 128, 64),
            (256, 128, 128, 64),
            (128, 128, 128, 128),
            (512, 256, 128, 64)
        ]
    }
    best_val_f1 = 0
    best_params = {}
    for struct in tuning_params['structs']:
        for lr in tuning_params['lrs']:
            for batch in tuning_params['batches']:
                temp_model = MLPClassifier(
                    hidden_layer_sizes=struct,
                    learning_rate_init=lr,
                    batch_size=batch,
                    max_iter=30,
                    tol=1e-4,
                    early_stopping=True,
                    n_iter_no_change=3,
                    random_state=42
                )
                temp_model.fit(X_tune, y_tune)
                curr_f1 = f1_score(y_val, temp_model.predict(X_val), average='macro')
                if curr_f1 > best_val_f1:
                    best_val_f1 = curr_f1
                    best_params = {
                        'lr': lr,
                        'batch': batch,
                        'struct': struct
                    }
    final_dnn = MLPClassifier(
        hidden_layer_sizes=best_params['struct'],
        learning_rate_init=best_params['lr'],
        batch_size=best_params['batch'],
        max_iter=100,
        tol=1e-4,
        early_stopping=True,
        n_iter_no_change=5,
        random_state=42
    )
    final_dnn.fit(X_train_val, y_train_val)
    test_preds = final_dnn.predict(X_test)
    acc = accuracy_score(y_test, test_preds)
    f1 = f1_score(y_test, test_preds, average='macro')
    all_results_tfidf.append({
        'Model': 'DNN (MLP)',
        'Dataset': name,
        'Accuracy': acc,
        'F1-Macro': f1
    })
    print(f"Accuracy: {acc:.4f}")
    print(f"F1-Score (Macro): {f1:.4f}\n")
    print("\nConfusion Matrix:\n")
    print(confusion_matrix(y_test, test_preds))
    print("\nClassification Report:\n")
    print(classification_report(y_test, test_preds))

df = pd.DataFrame(all_results_tfidf)
champions = df.groupby('Model').max().reset_index().sort_values(by='F1-Macro', ascending=False)
models = champions['Model'].values
accuracy = champions['Accuracy'].values
f1_macro = champions['F1-Macro'].values
x = np.arange(len(models))
width = 0.35
plt.style.use('ggplot')
fig, ax = plt.subplots(figsize=(10, 6))
bar1 = ax.bar(x - width/2, accuracy, width, label='Accuracy', color='#1F77B4', edgecolor='white', linewidth=0.7)
bar2 = ax.bar(x + width/2, f1_macro, width, label='F1-Macro', color='#AEC7E8', edgecolor='white', linewidth=0.7)
ax.set_xlabel('Model Name', fontweight='bold', fontsize=12)
ax.set_ylabel('Metric Score (0-1)', fontweight='bold', fontsize=12)
ax.set_title('Champion Model Performance Comparison (TF-IDF)', fontweight='bold', fontsize=14, pad=25)
ax.set_xticks(x)
ax.set_xticklabels(models, ha='right')
ax.set_ylim(0, 1.15)
ax.legend(loc='upper right', frameon=True, facecolor='white')
ax.yaxis.grid(True, linestyle='--', alpha=0.7)
def add_labels(rects):
    for rect in rects:
        height = rect.get_height()
        ax.annotate(f'{height:.4f}',
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 5),
                    textcoords="offset points",
                    ha='center', va='bottom',
                    fontweight='bold', fontsize=9)
add_labels(bar1)
add_labels(bar2)
plt.tight_layout()
plt.show()

for name, X in skipgram_results.items():
    print(f"{'='*40}")
    print(f"DATASET: {name}")
    print(f"{'='*40}\n")
    X_tv = X[:TRAIN_VAL_LIMIT].reshape(-1, 1, X.shape[1])
    y_tv = y[:TRAIN_VAL_LIMIT]
    X_test = X[TRAIN_VAL_LIMIT:].reshape(-1, 1, X.shape[1])
    y_test = y[TRAIN_VAL_LIMIT:]
    X_tr, X_val, y_tr, y_val = train_test_split(X_tv, y_tv, test_size=0.15, random_state=42, stratify=y_tv)
    X_tune, y_tune = resample(X_tr, y_tr, n_samples=10000, random_state=42, stratify=y_tr)
    lrs = [0.001, 0.0005]
    units = [128, 256]
    batches = [512, 1024]
    num_classes = len(np.unique(y))
    best_cfg = {'lr': 0.001, 'u': 128, 'b': 1024}
    best_f1 = 0
    for lr in lrs:
        for u in units:
            for b in batches:
                m = tf.keras.models.Sequential([
                    tf.keras.layers.Input(shape=(1, X_tv.shape[2])),
                    tf.keras.layers.SimpleRNN(u),
                    tf.keras.layers.Dense(128, activation='relu'),
                    tf.keras.layers.Dense(64, activation='relu'),
                    tf.keras.layers.Dense(num_classes, activation='softmax')
                ])
                m.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=lr), loss='sparse_categorical_crossentropy')
                m.fit(X_tune, y_tune, epochs=2, batch_size=b, verbose=0)
                val_preds = np.argmax(m.predict(X_val, verbose=0), axis=1)
                f1_temp = f1_score(y_val, val_preds, average='macro')
                if f1_temp > best_f1:
                    best_f1 = f1_temp
                    best_cfg = {'lr': lr, 'u': u, 'b': b}
    final_dnn = tf.keras.models.Sequential([
        tf.keras.layers.Input(shape=(1, X_tv.shape[2])),
        tf.keras.layers.SimpleRNN(best_cfg['u']),
        tf.keras.layers.Dense(256, activation='relu'),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(num_classes, activation='softmax')
    ])
    final_dnn.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=best_cfg['lr']),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    final_dnn.fit(
        X_tv, y_tv,
        epochs=30,
        batch_size=best_cfg['b'],
        validation_split=0.1,
        verbose=0,
        callbacks=[tf.keras.callbacks.EarlyStopping(patience=3, restore_best_weights=True)]
    )
    test_preds = np.argmax(final_dnn.predict(X_test, verbose=0), axis=1)
    acc = accuracy_score(y_test, test_preds)
    f1 = f1_score(y_test, test_preds, average='macro')
    all_results_skipgram.append({
        'Model': 'SimpleRNN',
        'Dataset': name,
        'Accuracy': acc,
        'F1-Macro': f1
    })
    print(f"Accuracy: {acc:.4f}")
    print(f"F1-Score (Macro): {f1:.4f}\n")
    print("Confusion Matrix:\n")
    print(confusion_matrix(y_test, test_preds))
    print("\nClassification Report:\n")
    print(classification_report(y_test, test_preds))

for name, X in skipgram_results.items():
    print(f"{'='*40}")
    print(f"DATASET: {name}")
    print(f"{'='*40}\n")
    X_tv = X[:TRAIN_VAL_LIMIT].reshape(-1, 1, X.shape[1])
    y_tv = y[:TRAIN_VAL_LIMIT]
    X_test = X[TRAIN_VAL_LIMIT:].reshape(-1, 1, X.shape[1])
    y_test = y[TRAIN_VAL_LIMIT:]
    X_tr, X_val, y_tr, y_val = train_test_split(X_tv, y_tv, test_size=0.15, random_state=42, stratify=y_tv)
    X_tune, y_tune = resample(X_tr, y_tr, n_samples=10000, random_state=42, stratify=y_tr)
    lrs = [0.001, 0.0005]
    units = [128, 256]
    batches = [512, 1024]
    num_classes = len(np.unique(y))
    best_cfg = {'lr': 0.001, 'u': 128, 'b': 1024}
    best_f1 = 0
    for lr in lrs:
        for u in units:
            for b in batches:
                m = tf.keras.models.Sequential([
                    tf.keras.layers.Input(shape=(1, X_tv.shape[2])),
                    tf.keras.layers.GRU(u),
                    tf.keras.layers.Dense(128, activation='relu'),
                    tf.keras.layers.Dense(64, activation='relu'),
                    tf.keras.layers.Dense(num_classes, activation='softmax')
                ])
                m.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=lr), loss='sparse_categorical_crossentropy')
                m.fit(X_tune, y_tune, epochs=2, batch_size=b, verbose=0)
                val_preds = np.argmax(m.predict(X_val, verbose=0), axis=1)
                f1_temp = f1_score(y_val, val_preds, average='macro')
                if f1_temp > best_f1:
                    best_f1 = f1_temp
                    best_cfg = {'lr': lr, 'u': u, 'b': b}
    final_dnn = tf.keras.models.Sequential([
        tf.keras.layers.Input(shape=(1, X_tv.shape[2])),
        tf.keras.layers.GRU(best_cfg['u']),
        tf.keras.layers.Dense(256, activation='relu'),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(num_classes, activation='softmax')
    ])
    final_dnn.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=best_cfg['lr']),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    final_dnn.fit(
        X_tv, y_tv,
        epochs=30,
        batch_size=best_cfg['b'],
        validation_split=0.1,
        verbose=0,
        callbacks=[tf.keras.callbacks.EarlyStopping(patience=3, restore_best_weights=True)]
    )
    test_preds = np.argmax(final_dnn.predict(X_test, verbose=0), axis=1)
    acc = accuracy_score(y_test, test_preds)
    f1 = f1_score(y_test, test_preds, average='macro')
    all_results_skipgram.append({
        'Model': 'GRU',
        'Dataset': name,
        'Accuracy': acc,
        'F1-Macro': f1
    })
    print(f"Accuracy: {acc:.4f}")
    print(f"F1-Score (Macro): {f1:.4f}\n")
    print("Confusion Matrix:\n")
    print(confusion_matrix(y_test, test_preds))
    print("\nClassification Report:\n")
    print(classification_report(y_test, test_preds))

for name, X in skipgram_results.items():
    print(f"{'='*40}")
    print(f"DATASET: {name}")
    print(f"{'='*40}\n")
    X_tv = X[:TRAIN_VAL_LIMIT].reshape(-1, 1, X.shape[1])
    y_tv = y[:TRAIN_VAL_LIMIT]
    X_test = X[TRAIN_VAL_LIMIT:].reshape(-1, 1, X.shape[1])
    y_test = y[TRAIN_VAL_LIMIT:]
    X_tr, X_val, y_tr, y_val = train_test_split(X_tv, y_tv, test_size=0.15, random_state=42, stratify=y_tv)
    X_tune, y_tune = resample(X_tr, y_tr, n_samples=10000, random_state=42, stratify=y_tr)
    lrs = [0.001, 0.0005]
    units = [128, 256]
    batches = [512, 1024]
    num_classes = len(np.unique(y))
    best_cfg = {'lr': 0.001, 'u': 128, 'b': 1024}
    best_f1 = 0
    for lr in lrs:
        for u in units:
            for b in batches:
                m = tf.keras.models.Sequential([
                    tf.keras.layers.Input(shape=(1, X_tv.shape[2])),
                    tf.keras.layers.LSTM(u),
                    tf.keras.layers.Dense(128, activation='relu'),
                    tf.keras.layers.Dense(64, activation='relu'),
                    tf.keras.layers.Dense(num_classes, activation='softmax')
                ])
                m.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=lr), loss='sparse_categorical_crossentropy')
                m.fit(X_tune, y_tune, epochs=2, batch_size=b, verbose=0)
                val_preds = np.argmax(m.predict(X_val, verbose=0), axis=1)
                f1_temp = f1_score(y_val, val_preds, average='macro')
                if f1_temp > best_f1:
                    best_f1 = f1_temp
                    best_cfg = {'lr': lr, 'u': u, 'b': b}
    final_dnn = tf.keras.models.Sequential([
        tf.keras.layers.Input(shape=(1, X_tv.shape[2])),
        tf.keras.layers.LSTM(best_cfg['u']),
        tf.keras.layers.Dense(256, activation='relu'),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(num_classes, activation='softmax')
    ])
    final_dnn.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=best_cfg['lr']),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    final_dnn.fit(
        X_tv, y_tv,
        epochs=30,
        batch_size=best_cfg['b'],
        validation_split=0.1,
        verbose=0,
        callbacks=[tf.keras.callbacks.EarlyStopping(patience=3, restore_best_weights=True)]
    )
    test_preds = np.argmax(final_dnn.predict(X_test, verbose=0), axis=1)
    acc = accuracy_score(y_test, test_preds)
    f1 = f1_score(y_test, test_preds, average='macro')
    all_results_skipgram.append({
        'Model': 'LSTM',
        'Dataset': name,
        'Accuracy': acc,
        'F1-Macro': f1
    })
    print(f"Accuracy: {acc:.4f}")
    print(f"F1-Score (Macro): {f1:.4f}\n")
    print("Confusion Matrix:\n")
    print(confusion_matrix(y_test, test_preds))
    print("\nClassification Report:\n")
    print(classification_report(y_test, test_preds))

for name, X in skipgram_results.items():
    print(f"{'='*40}")
    print(f"DATASET: {name}")
    print(f"{'='*40}\n")
    X_tv = X[:TRAIN_VAL_LIMIT].reshape(-1, 1, X.shape[1])
    y_tv = y[:TRAIN_VAL_LIMIT]
    X_test = X[TRAIN_VAL_LIMIT:].reshape(-1, 1, X.shape[1])
    y_test = y[TRAIN_VAL_LIMIT:]
    X_tr, X_val, y_tr, y_val = train_test_split(X_tv, y_tv, test_size=0.15, random_state=42, stratify=y_tv)
    X_tune, y_tune = resample(X_tr, y_tr, n_samples=10000, random_state=42, stratify=y_tr)
    lrs = [0.001, 0.0005]
    units = [128, 256]
    batches = [512, 1024]
    num_classes = len(np.unique(y))
    best_cfg = {'lr': 0.001, 'u': 128, 'b': 1024}
    best_f1 = 0
    for lr in lrs:
        for u in units:
            for b in batches:
                m = tf.keras.models.Sequential([
                    tf.keras.layers.Input(shape=(1, X_tv.shape[2])),
                    tf.keras.layers.Bidirectional(layers.SimpleRNN(u)),
                    tf.keras.layers.Dense(128, activation='relu'),
                    tf.keras.layers.Dense(64, activation='relu'),
                    tf.keras.layers.Dense(num_classes, activation='softmax')
                ])
                m.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=lr), loss='sparse_categorical_crossentropy')
                m.fit(X_tune, y_tune, epochs=2, batch_size=b, verbose=0)
                val_preds = np.argmax(m.predict(X_val, verbose=0), axis=1)
                f1_temp = f1_score(y_val, val_preds, average='macro')
                if f1_temp > best_f1:
                    best_f1 = f1_temp
                    best_cfg = {'lr': lr, 'u': u, 'b': b}
    final_dnn = tf.keras.models.Sequential([
        tf.keras.layers.Input(shape=(1, X_tv.shape[2])),
        tf.keras.layers.Bidirectional(layers.SimpleRNN(best_cfg['u'])),
        tf.keras.layers.Dense(256, activation='relu'),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(num_classes, activation='softmax')
    ])
    final_dnn.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=best_cfg['lr']),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    final_dnn.fit(
        X_tv, y_tv,
        epochs=30,
        batch_size=best_cfg['b'],
        validation_split=0.1,
        verbose=0,
        callbacks=[tf.keras.callbacks.EarlyStopping(patience=3, restore_best_weights=True)]
    )
    test_preds = np.argmax(final_dnn.predict(X_test, verbose=0), axis=1)
    acc = accuracy_score(y_test, test_preds)
    f1 = f1_score(y_test, test_preds, average='macro')
    all_results_skipgram.append({
        'Model': 'Bidirectional SimpleRNN',
        'Dataset': name,
        'Accuracy': acc,
        'F1-Macro': f1
    })
    print(f"Accuracy: {acc:.4f}")
    print(f"F1-Score (Macro): {f1:.4f}\n")
    print("Confusion Matrix:\n")
    print(confusion_matrix(y_test, test_preds))
    print("\nClassification Report:\n")
    print(classification_report(y_test, test_preds))

for name, X in skipgram_results.items():
    print(f"{'='*40}")
    print(f"DATASET: {name}")
    print(f"{'='*40}\n")
    X_tv = X[:TRAIN_VAL_LIMIT].reshape(-1, 1, X.shape[1])
    y_tv = y[:TRAIN_VAL_LIMIT]
    X_test = X[TRAIN_VAL_LIMIT:].reshape(-1, 1, X.shape[1])
    y_test = y[TRAIN_VAL_LIMIT:]
    X_tr, X_val, y_tr, y_val = train_test_split(X_tv, y_tv, test_size=0.15, random_state=42, stratify=y_tv)
    X_tune, y_tune = resample(X_tr, y_tr, n_samples=10000, random_state=42, stratify=y_tr)
    lrs = [0.001, 0.0005]
    units = [128, 256]
    batches = [512, 1024]
    num_classes = len(np.unique(y))
    best_cfg = {'lr': 0.001, 'u': 128, 'b': 1024}
    best_f1 = 0
    for lr in lrs:
        for u in units:
            for b in batches:
                m = tf.keras.models.Sequential([
                    tf.keras.layers.Input(shape=(1, X_tv.shape[2])),
                    tf.keras.layers.Bidirectional(layers.GRU(u)),
                    tf.keras.layers.Dense(128, activation='relu'),
                    tf.keras.layers.Dense(64, activation='relu'),
                    tf.keras.layers.Dense(num_classes, activation='softmax')
                ])
                m.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=lr), loss='sparse_categorical_crossentropy')
                m.fit(X_tune, y_tune, epochs=2, batch_size=b, verbose=0)
                val_preds = np.argmax(m.predict(X_val, verbose=0), axis=1)
                f1_temp = f1_score(y_val, val_preds, average='macro')
                if f1_temp > best_f1:
                    best_f1 = f1_temp
                    best_cfg = {'lr': lr, 'u': u, 'b': b}
    final_dnn = tf.keras.models.Sequential([
        tf.keras.layers.Input(shape=(1, X_tv.shape[2])),
        tf.keras.layers.Bidirectional(layers.GRU(best_cfg['u'])),
        tf.keras.layers.Dense(256, activation='relu'),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(num_classes, activation='softmax')
    ])
    final_dnn.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=best_cfg['lr']),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    final_dnn.fit(
        X_tv, y_tv,
        epochs=30,
        batch_size=best_cfg['b'],
        validation_split=0.1,
        verbose=0,
        callbacks=[tf.keras.callbacks.EarlyStopping(patience=3, restore_best_weights=True)]
    )
    test_preds = np.argmax(final_dnn.predict(X_test, verbose=0), axis=1)
    acc = accuracy_score(y_test, test_preds)
    f1 = f1_score(y_test, test_preds, average='macro')
    all_results_skipgram.append({
        'Model': 'Bidirectional GRU',
        'Dataset': name,
        'Accuracy': acc,
        'F1-Macro': f1
    })
    print(f"Accuracy: {acc:.4f}")
    print(f"F1-Score (Macro): {f1:.4f}\n")
    print("Confusion Matrix:\n")
    print(confusion_matrix(y_test, test_preds))
    print("\nClassification Report:\n")
    print(classification_report(y_test, test_preds))

for name, X in skipgram_results.items():
    print(f"{'='*40}")
    print(f"DATASET: {name}")
    print(f"{'='*40}\n")
    X_tv = X[:TRAIN_VAL_LIMIT].reshape(-1, 1, X.shape[1])
    y_tv = y[:TRAIN_VAL_LIMIT]
    X_test = X[TRAIN_VAL_LIMIT:].reshape(-1, 1, X.shape[1])
    y_test = y[TRAIN_VAL_LIMIT:]
    X_tr, X_val, y_tr, y_val = train_test_split(X_tv, y_tv, test_size=0.15, random_state=42, stratify=y_tv)
    X_tune, y_tune = resample(X_tr, y_tr, n_samples=10000, random_state=42, stratify=y_tr)
    lrs = [0.001, 0.0005]
    units = [128, 256]
    batches = [512, 1024]
    num_classes = len(np.unique(y))
    best_cfg = {'lr': 0.001, 'u': 128, 'b': 1024}
    best_f1 = 0
    for lr in lrs:
        for u in units:
            for b in batches:
                m = tf.keras.models.Sequential([
                    tf.keras.layers.Input(shape=(1, X_tv.shape[2])),
                    tf.keras.layers.Bidirectional(layers.LSTM(u)),
                    tf.keras.layers.Dense(128, activation='relu'),
                    tf.keras.layers.Dense(64, activation='relu'),
                    tf.keras.layers.Dense(num_classes, activation='softmax')
                ])
                m.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=lr), loss='sparse_categorical_crossentropy')
                m.fit(X_tune, y_tune, epochs=2, batch_size=b, verbose=0)
                val_preds = np.argmax(m.predict(X_val, verbose=0), axis=1)
                f1_temp = f1_score(y_val, val_preds, average='macro')
                if f1_temp > best_f1:
                    best_f1 = f1_temp
                    best_cfg = {'lr': lr, 'u': u, 'b': b}
    final_dnn = tf.keras.models.Sequential([
        tf.keras.layers.Input(shape=(1, X_tv.shape[2])),
        tf.keras.layers.Bidirectional(layers.LSTM(best_cfg['u'])),
        tf.keras.layers.Dense(256, activation='relu'),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(num_classes, activation='softmax')
    ])
    final_dnn.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=best_cfg['lr']),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    final_dnn.fit(
        X_tv, y_tv,
        epochs=30,
        batch_size=best_cfg['b'],
        validation_split=0.1,
        verbose=0,
        callbacks=[tf.keras.callbacks.EarlyStopping(patience=3, restore_best_weights=True)]
    )
    test_preds = np.argmax(final_dnn.predict(X_test, verbose=0), axis=1)
    acc = accuracy_score(y_test, test_preds)
    f1 = f1_score(y_test, test_preds, average='macro')
    all_results_skipgram.append({
        'Model': 'Bidirectional LSTM',
        'Dataset': name,
        'Accuracy': acc,
        'F1-Macro': f1
    })
    print(f"Accuracy: {acc:.4f}")
    print(f"F1-Score (Macro): {f1:.4f}\n")
    print("Confusion Matrix:\n")
    print(confusion_matrix(y_test, test_preds))
    print("\nClassification Report:\n")
    print(classification_report(y_test, test_preds))

df_skip = pd.DataFrame(all_results_skipgram)
champions_skip = df_skip.groupby('Model').max().reset_index().sort_values(by='F1-Macro', ascending=False)
models = champions_skip['Model'].values
accuracy = champions_skip['Accuracy'].values
f1_macro = champions_skip['F1-Macro'].values
x = np.arange(len(models))
width = 0.4
plt.style.use('ggplot')
fig, ax = plt.subplots(figsize=(12, 7))
bar1 = ax.bar(x - width/2, accuracy, width, label='Accuracy', color='#1F77B4', edgecolor='white', linewidth=0.7)
bar2 = ax.bar(x + width/2, f1_macro, width, label='F1-Macro', color='#AEC7E8', edgecolor='white', linewidth=0.7)
ax.set_xlabel('Architecture', fontweight='bold', fontsize=12)
ax.set_ylabel('Metric Score (0-1)', fontweight='bold', fontsize=12)
ax.set_title('Deep Learning Performance Comparison (Skip-gram)', fontweight='bold', fontsize=16, pad=30)
ax.set_xticks(x)
ax.set_xticklabels(models, rotation=45, ha='right', fontsize=10)
ax.set_ylim(0, 1.15)
ax.legend(loc='upper right', frameon=True, facecolor='white', shadow=False)
ax.yaxis.grid(True, linestyle='--', alpha=0.6)
def add_labels(rects):
    for rect in rects:
        height = rect.get_height()
        ax.annotate(f'{height:.4f}',
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 8),
                    textcoords="offset points",
                    ha='center', va='bottom',
                    fontweight='bold', fontsize=9)
add_labels(bar1)
add_labels(bar2)
plt.tight_layout()
plt.show()